- brmp/backend.py
- brmp/fit.py
- brmp/numpyro_backend.py
- brmp/pyro_backend.py
- tests/test_brm.py
This extends the `get_param` function to include a `preserve_chains` argument. This makes it possible to extract samples grouped by MCMC chain from a `fit` object.
The motivation for this is to make it possible to compute MCMC diagnostics. After this change is merged, we'll be able to do things like:
```python
import pandas as pd
import numpy as np
from brmp import defm
from brmp.fit import get_param
from numpyro.diagnostics import effective_sample_size, gelman_rubin
df = pd.DataFrame(dict(
y=np.random.randn(100),
))
fit = defm('y ~ 1', df).fit(iter=100, num_chains=2)
print(effective_sample_size(get_param(fit, 'b', True)))
print(gelman_rubin(get_param(fit, 'b', True)))
```
> Have `get_param` (optionally) return samples grouped by MCMC chain.

- brmp/__init__.py
- brmp/backend.py
- brmp/numpyro_backend.py
- brmp/pyro_backend.py
This change moves the default inference arguments that are shared across back ends to the methods of the `GenerateResult` class. The idea is that by doing so we make them easier to document, as these methods are part of the public interface.
Tests pass locally.
> Move shared default inference arguments to public inference methods.

- .travis.yml
- Makefile
- brmp/__init__.py
- brmp/backend.py
- brmp/design.py
- brmp/family.py
- brmp/fit.py
- brmp/formula.py
- brmp/model.py
- brmp/model_pre.py
- brmp/numpyro_backend.py
- brmp/numpyro_codegen.py
- brmp/priors.py
- brmp/pyro_backend.py
- brmp/pyro_codegen.py
- brmp/utils.py
- docs/source/conf.py
- setup.py
- tests/test_brm.py
There is purely a formatting change. 
- Adds fixes from flake8;  running `make test` in travis will run the linter.
- Adds `make docs` and `make lint` commands to the `Makefile`. Note that to reformat imports, we can use `make format`.
@null-a - Since these changes pervade the codebase, we could defer merging if you have any major PRs that you are currently working on, so that you can avoid merge conflicts.
Fixes #5, #36.
> Fixes to comply with flake8

- Makefile
- tests/test_brm.py
This is a minor re-organisation of some tests to improve the coverage we get from CI tests. Previously the tests which exercised the nuts method of the numpyro backend were hidden behind the `RUN_SLOW` flag, and these were not included in CI. I've now dropped this flag.
To keep a lid on the time it takes to run the entire suite, I've reduced the number of tests which use numpyro's `nuts` method. This was achieved by (a) switching to running some "parameter shape" tests using only the `prior` algorithm, and (b) splitting out cases related to "new data" from `test_marginals_and_fitted_smoke`. I think we lose very little by doing this -- I think it's a good trade-off.
Fixes #48.
> Run more tests on CI

- brmp/numpyro_codegen.py
- brmp/pyro_backend.py
- brmp/pyro_codegen.py
- brmp/utils.py
- tests/test_brm.py
Fixes #38 in a more general way.
This is used to augment information in the stack trace when the generated model throws any exception. A `traceback_generated` context-manager is provided, which can be used as follows:
```python
with traceback_generated(model.code):
model.fn(**data)
```
If the error originates from running the model code, this will augment the stack trace with the model code highlighting the line that throws the error, otherwise this will have no effect. I have only used this in one part of the code that was throwing an exception with Pyro's dev branch, but we can use this more widely if it turns out to be useful. Turns out the AssertionError was due to these lines which I recently fixed in dev 😆, so this wasn't anything alarming:
```
if num_chains == 1:
samples = {k: …
```
> Augment exception message when running generated code

- brmp/examples/Africa.ipynb
- brmp/examples/Baseball.ipynb
- brmp/fit.py
- docs/source/fit.rst
- tests/test_brm.py
This moves `marginals`, `fitted` etc. from top-level methods to methods on the `Fit` class. (Closes #50.)
I'm personally happy with either approach, but I'm guessing the change is worth making since the result is arguably more idiomatic. Agreed?
> Move methods on to `Fit` class.

- docs/requirements.txt
This is needed to publish the docs on readthedocs. 
cc @jpchen - let me know if we need to make any changes.
> Add requirements.txt for doc generation

- brmp/__init__.py
- brmp/numpyro_backend.py
- brmp/pyro_backend.py
- tests/test_brm.py
The numpyro methods `nuts` and `prior` currently take a `seed` argument, which does the obvious thing. This PR adds a similar argument to the pyro methods `nuts`, `svi` and `prior`. This argument is now available uniformly across inference methods, and I've updated the docs to reflect this. This PR also adds some basic tests.
(Partially addresses #11.)
> Support a `seed` argument across all inference methods.

- brmp/fit.py
- brmp/numpyro_backend.py
- brmp/numpyro_codegen.py
- brmp/pyro_backend.py
- tests/test_brm.py
Closes #11.
BTW, this is where #61 was useful. Because we're now not calling the generated `sample_response_fn` directly (e.g. from `fitted`), back ends have the opportunity to apply the seed handler to the generated code.
> Allow rng seed to be given to `fit.fitted(what='sample')`.

- docs/requirements.txt
- docs/source/conf.py
Addresses #4 - getting RTD build to work correctly for brmp. [link](https://brmp.readthedocs.io/en/fix-build/) to docs for the built branch.
> Fix RTD build by using small sized CPU wheels for PyTorch

- brmp/__init__.py
- brmp/design.py
- brmp/examples/Africa.ipynb
- brmp/examples/Baseball.ipynb
- brmp/examples/Priors.ipynb
- brmp/fit.py
- brmp/priors.py
- docs/source/brmp.rst
- tests/test_brm.py
The aim of this PR is to (a) simplify the public interface for defining models and running inference (partially addressing #32), and (b) to introduce a new interface (for the same purpose) that is less convenient but more flexible.
The main change to the public interface is that there is no longer an explicit `generate` step when defining a model. A further minor change is that `defm` is renamed to `brm`. For example:
```python
fit = defm('y ~ x', df).generate(numpyro).fit(algo='nuts', iter=10)
fit = brm('y ~ x', df).fit(algo='nuts', iter=10, backend=numpyro)
fit = brm('y ~ x', df).nuts(iter=10, backend=numpyro)
```
While it was already possible to avoid explicitly calling `generate`, its presence in the docs makes things seem a bit more complicated than they need to be. I think this …
> Interface changes

- brmp/__init__.py
- brmp/backend.py
- brmp/examples/Baseball.ipynb
- brmp/fit.py
- brmp/numpyro_backend.py
- brmp/numpyro_codegen.py
- brmp/pyro_backend.py
- brmp/pyro_codegen.py
This PR (only) renames a few things.
The motivation is to have the new `define_model` method (#68) return a `Model` instance, rather than a `DefineModelResult`. To make this possible I've renamed the existing `Model` class (in `backend.py`) to `Assets`. (`Assets` is just a tuple of Python code/functions generated by a backend, given a model description.)
I've also renamed `GenResult` to `AssetWrapper`. This is much less important than the above, but it seemed a bit nicer to me.
> Rename some things

- brmp/__init__.py
- brmp/backend.py
- tests/test_brm.py
This PR makes NumPyro the default backend when using NUTS to fit a model. (Closes #55.)
(I changed the `__repr__` method on `Backend` to make the docs a little nicer to read where a `Backend` appears as a default argument.)
> Adjust default backends

- .readthedocs.yml
- docs/requirements.txt
- docs/requirements_torch.txt
- docs/source/conf.py
- setup.py
- tests/test_brm.py
Additionally, attempts to fix #70. 
The issue is that we cannot enforce order in a `requirements.txt` file and since PyTorch released a  version `1.3.1` very recently, we were fetching a bigger file from pypi instead of the `1.3.0` cpu only hosted wheels (this was being fetched as a dependency of `pyro-ppl`). We could have fixed that by updating the torch dependency in `requirements.txt` to `1.3.1`, but this would be a recurring issue with each update to pytorch. 
Instead, the current workaround splits the installs into 2 requirement files - pytorch install + remaining, which should be more stable. 
[build](https://readthedocs.org/projects/brmp/builds/9982731/)
> Update Pyro to version 1.0

- tests/test_brm.py
This is a minor change that replaces `test_expected_response_codegen` with a new test that's similar to the recently added `test_mu_correctness`. I think this is an improvement because it actually exercises `fit.fitted(what='expectation')`. I think the cases are a little easier to read this way too.
(Related: #15)
> Test expectation via public API.

- brmp/model.py
- tests/test_brm.py
This fixes #62. The root cause of that was a failure to correctly generate parameter names for a model when the levels of a category were not already strings. The test added here fails without the fix in this PR.
> Allow integers to be used as categorical levels.

- tests/test_brm.py
This PR extends the code generation tests to check that the response is correctly observed when evaluating the model.
Partially addresses #15.
> Extend code generation tests to check that response is observed

- LICENSE.md
- setup.py
Refer to https://github.com/pyro-ppl/pyro/issues/2249, in accordance with the rest of the Pyro project. I think we can defer adding file specific copyright / license info until we release.
> Add Apache 2.0 license

- brmp/fit.py
This PR addresses a TODO comment in the `marginals` function where the scalar parameter map is rebuilt on each call to `get_scalar_param`.
I've tested this with a model that has around 40000 parameters and it takes the run time of `marginals` from around 7 hrs. on a Mac Book Pro to around 220 seconds. I've also verified that the existing pytest tests work as before.
This is my first contribution to this project so please let me know if there are any guidelines or other things I need to do for a PR.
> calculate scalar parameter map once on init to avoid rebuilding multiple times

- brmp/family.py
- brmp/numpyro_codegen.py
- brmp/pyro_codegen.py
- tests/test_brm.py
This PR addresses adding support for a Poisson family likelihood. I've tested that it works in both numpyro and pyro.
Reading through this issue, it looks like there was previous discussion of adding Poisson support: https://github.com/pyro-ppl/brmp/issues/56
I think this PR addresses everything but the gamma prior. Was the intent to support an overdispersed Poisson by default?
I'm not super familiar with BRMS, and I couldn't tell from the docs whether they support a standard Poisson or overdispersed version.
> support for poisson
